# Generated by Django 4.0.3 on 2022-05-17 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_image_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookitem',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
        migrations.AddField(
            model_name='laptopitem',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
        migrations.AddField(
            model_name='shoesitem',
            name='item',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='product.item'),
        ),
    ]
