# Generated by Django 4.0.3 on 2022-05-17 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_image_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cname',
        ),
        migrations.AddField(
            model_name='item',
            name='cate',
            field=models.IntegerField(default=0),
        ),
    ]
